plugin:
  chatradius: 100
  prefix: '&e[ChatRadius] &r'
  update-check: true
  ##If set to false you will not longer get the messages "no update available" if you join the server
  no-update-available-message-on-join: false
storage:
  spy: true
  broadcast: true
